[project]
name = "clj"
version = "0.5.0"
description = "Utilities for lazy iterables"
authors = [{ name = "Baptiste Fontaine", email = "b@ptistefontaine.fr" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "clj",
    "clojure",
    "lazy",
    "iterables",
    "generators",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]

[project.urls]
Homepage = "https://github.com/bfontaine/clj"
Repository = "https://github.com/bfontaine/clj"

[dependency-groups]
dev = [
    "mypy>=2,<3",
    "pytest>=8.3,<9",
    "pytest-cov>=7,<8",
    "ruff>=0.16.9",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""
source-include = ["clj/py.typed"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
