[project]
name = "clj"
version = "0.6.0"
description = "Utilities for lazy iterables"
authors = [{ name = "Baptiste Fontaine", email = "b@ptistefontaine.fr" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "clj",
    "clojure",
    "lazy",
    "iterables",
    "generators",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]

[project.urls]
Homepage = "https://github.com/bfontaine/clj"
Repository = "https://github.com/bfontaine/clj"

[dependency-groups]
dev = [
    "mypy>=2,<3",
    "pytest>=8.3,<9",
    "pytest-cov>=7,<8",
    "ruff>=0.16.9",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""
source-include = ["clj/py.typed"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
target-version = "py311"
[tool.ruff.lint]
select = [
    "D", # docstrings
    "PERF", # Performance
    "W",
    "F",
    "UP", # deprecated Python
    # Flake8
    "A",
    "B",
    "C4",
    "PIE800",
    "PT",
    "SIM",
    "SLOT",
    "YTT",

    "PLE",
    "FURB",
    "PLC0207",
]
ignore = [
    "A001", "A004", # shadowed builtins
    "B007", # TODO: mark the code instead

    "D100", # "Missing docstring in public module"
    "D104", # "Missing docstring in public package"
    "D205", # "1 blank line required between summary line and description",
    "D401", # "First line of docstring should be in imperative mood"
]
