name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          python_version: "3.9"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          poetry_install_options: "--without dev"

